# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    app.command.primes:
        class: AppBundle\Command\PrimesCommand
        arguments:
            - "app:primes"
            - "@app.prime_generator"
        tags:
            - { name: console.command }

    app.prime_generator:
        class: AppBundle\Math\Prime
